version: "3"

services:
  smart-irrigation-app:
    image: waziup/smart-irrigation-waziapp:beta
    container_name: waziup.smart-irrigation-waziapp
    build:
      context: ./
    volumes:
      #- ./:/root/src/  # Uncomment for development
      - ./:/root/app # The unix socket has to have this name and be in ./ : proxy.sock
    privileged: false
    environment:
      - TEST_VAR=1
    healthcheck:
      test: curl --fail --unix-socket /root/app/proxy.sock http://localhost/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes
    restart: always # Uncomment to always restart


networks:
  default:
    external: # added because it is preexisting
      name: wazigate

