version: "3"

services:
  intel-irris:
    image: waziup/intel-irris-waziapp:dev
    container_name: waziup.intel-irris-waziapp
    build:
      context: ./
    volumes:
      - /var/lib/wazigate/apps/waziup.intel-irris-waziapp:/var/lib/waziapp/
      #- /var/lib/wazigate/apps/waziup.intel-irris-waziapp/static:/var/lib/waziapp/
    restart: unless-stopped
    environment:
      - TEST_VAR=1
    healthcheck:
      test: curl --fail --unix-socket /var/lib/waziapp/proxy.sock http://localhost/ || exit 1 
      interval: 30s
      retries: 10 # Will try for 5 minutes
    ports: #comment to run on unix
      - "5000:5000" #comment to run on unix
    network_mode: "host"

networks:
  default:
    external:
      name: wazigate
